version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "feat(openai)"
    allow:
      - dependency-name: 'openai'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
